POST http://localhost:3001/posts
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphcXVlLmRldW5lckBnb29nbGUuY29tIiwiaWQiOiI2NGE1YWRjMzQwY2I4MDE0ZmFjYTA2MzciLCJpYXQiOjE2ODkxNjY3ODd9.yo530rKMt2jYI_lD4ZrmMmDldnK861Dl39XyKfByIzs

{
    "title": "teste",
    "artist": "a",
    "url": "a"
}